@startuml MeS Dessin mode Proportionnel/Personnalisé/Parpoint Move

start
!theme blueprint

if (Le Rectangle de sélection est actif?) then (oui)
 
  if (La Vue est intégralement visible à l'écran?) then (oui)

    if (Coordonnées du curseur au sein de la Vue?) then (oui)
      :Affecter la position du curseur ou du doigt au point Courant(x,y);

      if (Mode différend de Par Point?) then (oui)
        #maroon:Calculer les coordonnées du Rectangle de sélection;
      else (non)
        stop;
      endif

    else (non)
      stop;
    endif

  else (non)
    stop;
  endif

else (non)
  stop;
endif

:Redessiner le Rectangle de Sélection;

stop